NDefines.NGame.START_DATE = "1770.1.1.12"
NDefines.NGame.END_DATE = "1800.1.1.1" 
NDefines.NGame.HANDS_OFF_START_TAG = "ZZZ"
NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 7
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 5
NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "1800.1.1.12"